#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING. If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
# 
#  file: command/rune_prio
#  version: 1.3
#  coder: Simone De Gregori
#
#####################################
set +e # continue on errors
prio_nice () {
# count=1
# for pid in $(pgrep -w mpd);
# do
    # if ((count == 3))
    # then
        # echo "### Set priority for: mpd-player thread ###";
        # renice -16 $pid;
    # fi
    # if ((count == 4))
    # then
        # echo "### Set priority for: mpd-output thread ###";
        # renice -18 $pid;
    # fi
    # if ((count == 5))
    # then
            # echo "### Set priority for: mpd-decoder thread ###";
            # renice -16 $pid;
    # fi
# count=$((count+1))
# done
renice -1 $(ps -Teo spid,pid,ni,pri,fname | grep -i ' mpd' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
renice -1 $(pgrep -wx shairport-sync)
renice -1 $(pgrep -wx spopd)
renice -1 $(pgrep -wx upmpdcli)
renice 10 $(ps -Teo spid,pid,ni,pri,fname | grep -i ' chromium' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
renice 10 $(pgrep -wx chromium)
renice 3 $(pgrep -wx ashuffle)
renice 3 $(pgrep -wx local-browser)
renice 3 $(pgrep -wx mpdscribble)
renice 2 $(pgrep -wx nmbd)
renice 2 $(pgrep -wx nmb)
renice 3 $(pgrep -wx rune_PL_wrk)
renice 3 $(pgrep -wx rune_SSM_wrk)
renice 3 $(pgrep -wx rune_SY_wrk)
renice 2 $(pgrep -wx smbd)
renice 2 $(pgrep -wx smb)
renice 2 $(pgrep -wx sshd)
renice 2 $(pgrep -wx xinit)
renice 1 $(pgrep -wx Xorg)
renice 1 $(pgrep -wx matchbox-window)
renice 2 $(pgrep -wx xbindkeys)
}

prio_default () {
# count=1
# for pid in $(pgrep -w mpd);
# do
    # if ((count == 3))
    # then
        # echo "### Set priority for: mpd-player thread ###";
        # renice 0 $pid;
    # fi
    # if ((count == 4))
    # then
        # echo "### Set priority for: mpd-output thread ###";
        # renice 0 $pid;
    # fi
    # if ((count == 5))
    # then
        # echo "### Set priority for: mpd-decoder thread ###";
        # renice 0 $pid;
    # fi
# count=$((count+1))
# done
renice 0 $(ps -Teo spid,pid,ni,pri,fname | grep -i ' mpd' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
renice 0 $(pgrep -wx shairport-sync)
renice 0 $(pgrep -wx spopd)
renice 0 $(pgrep -wx upmpdcli)
# renice 0 $(ps -Teo spid,pid,ni,pri,fname | grep -i ' chromium' | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 1)
# renice 0 $(pgrep -wx chromium)
renice 0 $(pgrep -wx ashuffle)
renice 0 $(pgrep -wx local-browser)
renice 0 $(pgrep -wx mpdscribble)
renice 0 $(pgrep -wx nmbd)
renice 0 $(pgrep -wx nmb)
renice 0 $(pgrep -wx rune_PL_wrk)
renice 0 $(pgrep -wx rune_SSM_wrk)
renice 0 $(pgrep -wx rune_SY_wrk)
renice 0 $(pgrep -wx smbd)
renice 0 $(pgrep -wx smb)
renice 0 $(pgrep -wx sshd)
renice 0 $(pgrep -wx xinit)
renice 0 $(pgrep -wx Xorg)
renice 0 $(pgrep -wx matchbox-window)
renice 0 $(pgrep -wx xbindkeys)
}

if [ "$1" == "default" ]; then
    echo "set default priority settings"
    prio_default
    exit 0
fi

if [ "$1" == "nice" ]; then
    echo "set nice priority settings"
    prio_nice
    exit 0
fi

echo "RuneAudio process priority settings"
echo "Usage: $0 {default|nice}"
exit 1
