#!/usr/bin/php
<?php
/*
 * Copyright (C) 2013-2015 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2015 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2015 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2015 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/upmpdcli_toggle
 *  version: 1.5
 *  date: july 2018
 *  coder: janui
 */
// common include
ini_set('display_errors', '1');
error_reporting(E_ALL);
ini_set('error_log', '/var/log/runeaudio/upmpdcli_toggle.log');
define('APP', '/srv/http/app/');
require_once('/srv/http/app/libs/runeaudio.php');

// Connect to Redis backend
$redis = new Redis();
$redis->connect('/run/redis/socket');

// clear the log file
sysCmd('echo "--------------- start: airplay_toggle ---------------" > /var/log/runeaudio/upmpdcli_toggle.log');

// read status from /usr/lib/systemd/system/upmpdcli.service
$status = $argv[1]; // "onstart", "onplay", "onpause", "onstop"

switch($status) {
    case "onstart":
        // start UPnP / DLNA
        wrk_startUpmpdcli($redis);
        // send notify
        ui_notify('UPnP / DLNA', 'Playback has been switched to an incoming UPnP / DLNA stream.');
        break;
    case "onplay":
        // play UPnP / DLNA
        wrk_playUpmpdcli($redis);
        // send notify
        ui_notify('UPnP / DLNA', 'Playback started.');
        break;
    case "onpause":
        // play UPnP / DLNA
        wrk_pausedUpmpdcli($redis);
        // send notify
        ui_notify('UPnP / DLNA', 'Playback paused.');
        break;
    case "onstop":
        // stop UPnP / DLNA
        wrk_stopUpmpdcli($redis);
        // send notify
        ui_notify('UPnP / DLNA', 'UPnP / DLNA playback has completed. The player is now unlocked.');
        break;
}

// update player view
ui_libraryHome($redis, 'Server');
