#!/bin/bash
export XDG_CACHE_HOME="/tmp/.cache" &
export DISPLAY=":0" &

# start the touchscreen calibration utility
# needed for some screens (Pollin 7" tft)
# for this to work you have to disable loading midori
#xinput_calibrator &

# set power management options
xset dpms 0 0 0 &

#turn screensaver off
xset s off &

# turn off screensaver
xset -dpms &

# start the window manager without titlebar and mouse
matchbox-window-manager -use_titlebar no -use_cursor no &

# install multimedia keyboard shortcuts
sudo -u http xbindkeys -f /srv/http/.xbindkeysrc -X :0 &

# start midori in private mode with fullscreen display
# sudo -u http midori -p -e Fullscreen -a http://localhost --display=:0
# midori -p -e Fullscreen http://localhost
# use chromium instead because it scales whereas Midori no longer does
sudo -u http /usr/bin/chromium --kiosk --incognito --force-device-scale-factor=1 -e http://localhost/
