#!/usr/bin/php
<?php
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: db/redis_acards_details
 *  version: 1.3
 *  coder: Simone De Gregori
 *
 */
// common include
include('/srv/http/app/config/config.php');
// ini_set('display_errors',1);
// error_reporting('E_ALL');
// acards_details database
$redis->Del('acards_details');
$redis->hSet('acards_details', 'AML-M8AUDIO', '{"sysname":"AML-M8AUDIO","extlabel":"ODROID HDMI","card_option":"buffer_time\t\"0\"","mixer_numid":"1","hwplatformid":"09","type":"integrated"}');
$redis->hSet('acards_details', 'ARCAM USB Audio 2.0', '{"sysname":"ARCAM USB Audio 2.0","extlabel":"Arcam rDAC","mixer_numid":"3","mixer_control":"ARCAM Clock Selector","type":"usb"}');
$redis->hSet('acards_details', 'AudioQuest DragonFly', '{"sysname":"AudioQuest DragonFly","extlabel":"AudioQuest DragonFly DAC","mixer_numid":"3","mixer_control":"PCM","type":"usb"}');
$redis->hSet('acards_details', 'Bel Canto 2496 USB', '{"sysname":"Bel Canto 2496 USB","extlabel":"Bel Canto 2496","card_option":"format\t\"96000:24:2\"","mixer_numid":"1","hwplatformid":"08","type":"usb"}');
$redis->hSet('acards_details', 'BossDAC', '{"sysname":"BossDAC","extlabel":"ALLO Boss DAC (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"08","type":"i2s"}'); 
$redis->hSet('acards_details', 'C-Media USB Headphone Set', '{"sysname":"C-Media USB Headphone Set","extlabel":"C-Media USB Headphone Set","mixer_numid":"7","mixer_control":"Headphone","type":"usb"}');
$redis->hSet('acards_details', 'Devialet USB Audio 2.0', '{"sysname":"Devialet USB Audio 2.0","extlabel":"Devialet Audio","mixer_numid":"3","mixer_control":"Devialet Clock Selector","type":"usb"}');
$redis->hSet('acards_details', 'DigiHug USB Audio', '{"sysname":"DigiHug USB Audio","extlabel":"DigiHug USB DAC","mixer_numid":"1","mixer_control":"PCM","hwplatformid":"08","type":"usb"}');
$redis->hSet('acards_details', 'Geek Out HD Audio 1V0', '{"sysname":"Geek Out HD Audio 1V0","extlabel":"LH Labs Geek Out 720","mixer_numid":"3","mixer_control":"LH Labs Clock Selector","type":"usb"}');
$redis->hSet('acards_details', 'Hugo', '{"sysname":"Hugo","extlabel":"Chord Hugo","mixer_numid":"4","mixer_control":"Hugo","type":"usb"}');
$redis->hSet('acards_details', 'I-Sabre Q2M DAC', '{"sysname":"I-Sabre Q2M DAC","extlabel":"I-Sabre Q2M DAC (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'IQaudIODAC', '{"sysname":"snd_rpi_iqaudio_dac","extlabel":"IQaudIO Pi-DAC+ (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"02","type":"i2s"}');
$redis->hSet('acards_details', 'NuForce USB Audio', '{"sysname":"NuForce USB Audio","extlabel":"NuForce DDA-100","mixer_numid":"4","mixer_control":"PCM","type":"usb"}');
$redis->hSet('acards_details', 'ODROID-DAC', '{"sysname":"ODROID-DAC","extlabel":"ODROID HifiShield (I&#178;S)","mixer_numid":"1","hwplatformid":"10","type":"i2s"}');
$redis->hSet('acards_details', 'ODROID-HDMI', '{"sysname":"ODROID-HDMI","extlabel":"ODROID-C2 HDMI","mixer_numid":"1","hwplatformid":"10","type":"integrated"}');
$redis->hSet('acards_details', 'PianoDAC', '{"sysname":"PianoDAC","extlabel":"ALLO Piano DAC (I&#178;S)","card_option":"format\t\"*:32:*\"","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"08","type":"i2s"}'); 
$redis->hSet('acards_details', 'PianoDACPlus', '{"sysname":"PianoDACPlus","extlabel":"ALLO Piano DAC 2.1(I&#178;S)","card_option":"format\t\"*:32:*\"","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"08","type":"i2s"}'); 
$redis->hSet('acards_details', 'Rotel PC-USB', '{"sysname":"Rotel PC-USB","extlabel":"Rotel USB","type":"usb"}');
$redis->hSet('acards_details', 'SA9023 USB Audio', '{"sysname":"SA9023 USB Audio","extlabel":"HiFimeDIY SABRE U2","mixer_numid":"4","mixer_control":"PCM","type":"usb"}');
$redis->hSet('acards_details', 'UAC1 DAC', '{"sysname":"UAC1 DAC","extlabel":"ObjectiveDAC (ODAC)","mixer_numid":"3","mixer_control":"PCM","type":"usb"}');
$redis->hSet('acards_details', 'USB Audio CODEC', '{"sysname":"USB Audio CODEC","extlabel":"Behringer U-CONTROL UCA202","mixer_numid":"3","mixer_control":"PCM","type":"usb"}');
$redis->hSet('acards_details', 'USB Sound Device', '{"sysname":"USB Sound Device","extlabel":"Cmedia CM2606","mixer_numid":"7","mixer_control":"Speaker","type":"usb"}');
$redis->hSet('acards_details', 'XMOS USB Audio 2.0', '{"sysname":"XMOS USB Audio 2.0","extlabel":"XMOS AK4399 USB-Audio DAC","mixer_numid":"3","mixer_control":"XMOS Clock Selector","type":"usb"}');
$redis->hSet('acards_details', 'bcm2835 ALSA', '{"sysname":"bcm2835 ALSA","extlabel":"none","hwplatformid":"01","type":"integrated_sub"}');
$redis->hSet('acards_details', 'berrynos', '{"sysname":"snd_rpi_hifiberry_dac","extlabel":"BerryNOS 1543 (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'berrynosmini', '{"sysname":"snd_rpi_hifiberry_dac","extlabel":"BerryNOS mini (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'imx-hdmi-soc', '{"sysname":"imx-hdmi-soc","extlabel":"Utilite HDMI Out","hwplatformid":"05","type":"integrated"}');
$redis->hSet('acards_details', 'imx-spdif', '{"sysname":"imx-spdif","extlabel":"Utilite Coax SPDIF Out","hwplatformid":"05","type":"integrated"}');
$redis->hSet('acards_details', 'raspyplay3', '{"sysname":"snd_rpi_hifiberry_dac","extlabel":"RaspyPlay3 (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'raspyplay4', '{"sysname":"snd_rpi_iqaudio_dac","extlabel":"RaspyPlay4 (I&#178;S)","mixer_numid":"1","mixer_control":"Playback Digital","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_hifiberry_amp', '{"sysname":"snd_rpi_hifiberry_amp","extlabel":"HifiBerry Amp+ (I&#178;S)","mixer_numid":"1","mixer_control":"Master","hwplatformid":"08","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_hifiberry_dac', '{"sysname":"snd_rpi_hifiberry_dac","extlabel":"HiFiBerry DAC (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_hifiberry_dacplus', '{"sysname":"snd_rpi_hifiberry_dacplus","extlabel":"HiFiBerry DAC+ (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_hifiberry_digi', '{"sysname":"snd_rpi_hifiberry_digi","extlabel":"HiFiBerry Digi (I&#178;S)","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_iqaudio_dac', '{"sysname":"snd_rpi_iqaudio_dac","extlabel":"IQaudIO Pi-DAC (I&#178;S)","mixer_numid":"1","mixer_control":"Playback Digital","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'wm8731-audio', '{"sysname":"wm8731-audio","extlabel":"Utilite Analog Out","mixer_numid":"1","mixer_control":"Master","hwplatformid":"05","type":"integrated"}');
$redis->hSet('acards_details', 'snd_rpi_rpi_dac', '{"sysname":"snd_rpi_rpi_dac","extlabel":"RPi DAC (I&#178;S)","hwplatformid":"08","type":"i2s"}');
// Two alternative versions of the rpi-dac configuration specifically for the es9023 DAC - in principal this DAC will only work for bitrates up to 192k
// The above line will provide bitrates up to 384k, these below are limited to 192k - if all your music is less than 192k then do nothing (most is 44.1k)
// Test each for your personal preference - comment out the previous line and uncomment one of the following lines
// $redis->hSet('acards_details', 'snd_rpi_rpi_dac', '{"sysname":"snd_rpi_rpi_dac","extlabel":"RPi DAC (I&#178;S)","card_option":"allowed_formats\t\"8000:24:2 16000:24:2 11025:24:2 22050:24:2 32000:24:2 37800:24:2 44056:32:2 44100:24:2 47250:32:2 48000:24:2 50000:24:2 54000:24:2 64000:24:2 88200:24:2 96000:24:2 176400:24:2 192000:24:2\"","hwplatformid":"08","type":"i2s"}'); 
// $redis->hSet('acards_details', 'snd_rpi_rpi_dac', '{"sysname":"snd_rpi_rpi_dac","extlabel":"RPi DAC (I&#178;S)","card_option":"format\t\"192000:24:2\"","hwplatformid":"08","type":"i2s"}'); 
$redis->hSet('acards_details', 'snd_rpi_justboom_dac', '{"sysname":"snd_rpi_justboom_dac","extlabel":"JustBoom DAC (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
$redis->hSet('acards_details', 'snd_rpi_wsp', '{"sysname":"snd_rpi_wsp","extlabel":"none","hwplatformid":"01","type":"integrated_sub"}');
//
// The following lines are NOT TESTED but provide a best guess implementation of several newer audio overlay profiles
// These lines should only be switched on if something does NOT work, it it actually fixes something then please post the results in the forum
//$redis->hSet('acards_details', 'snd_rpi_dionaudio_loco', '{"sysname":"snd_rpi_dionaudio_loco","extlabel":"Dionaudio Loco DAC-AMP (I&#178;S)","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_dionaudio_loco_v2', '{"sysname":"snd_rpi_dionaudio_loco_v2","extlabel":"Dionaudio Loco V2 DAC-AMP (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_iqaudio_digi', '{"sysname":"snd_rpi_iqaudio_digi","extlabel":"IQaudIO Digi wm8804 audio (I&#178;S)","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_rra_digidac1_soundcard', '{"sysname":"snd_rpi_rra_digidac1_soundcard","extlabel":"Red Rocks Audio DigiDAC1 soundcard (I&#178;S)","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_digidac1_soundcard', '{"sysname":"snd_rpi_digidac1_soundcard","extlabel":"Red Rocks Audio DigiDAC1 soundcard (I&#178;S)","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_fe_pi_audio', '{"sysname":"snd_rpi_fe_pi_audio","extlabel":"Fe-Pi Audio Sound Card (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_audioinjector_octo_soundcard', '{"sysname":"snd_rpi_audioinjector_octo_soundcard","extlabel":"Audioinjector Addons (I&#178;S)","mixer_numid":"1","mixer_control":"Master","hwplatformid":"05","type":"integrated"}');
//$redis->hSet('acards_details', 'snd_rpi_audioinjector_pi_soundcard', '{"sysname":"snd_rpi_audioinjector_pi_soundcard","extlabel":"Audioinjector WM8731 Audio (I&#178;S)","mixer_numid":"1","mixer_control":"Master","hwplatformid":"05","type":"integrated"}');
//$redis->hSet('acards_details', 'snd_rpi_raspidac3', '{"sysname":"snd_rpi_raspidac3","extlabel":"RaspiDAC3 (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
//$redis->hSet('acards_details', 'snd_rpi_rpi_cirrus', '{"sysname":"snd_rpi_rpi_cirrus","extlabel":"RPi Cirrus WM5102 (I&#178;S)","mixer_numid":"1","mixer_control":"Digital","hwplatformid":"01","type":"i2s"}');
//
$redis->sAdd('bcm2835 ALSA', '{"id":"1","sysname":"bcm2835 ALSA","extlabel":"RaspberryPi Analog Out","hwplatformid":"01","mixer_numid":"1","mixer_control":"PCM","route_cmd":"amixer -c *CARDID* cset numid=3 1 > /dev/null"}');
$redis->sAdd('bcm2835 ALSA', '{"id":"2","sysname":"bcm2835 ALSA","extlabel":"RaspberryPi HDMI Out","hwplatformid":"01","mixer_numid":"1","mixer_control":"PCM","route_cmd":"amixer -c *CARDID* cset numid=3 2 > /dev/null"}');
$redis->sAdd('snd_rpi_wsp', '{"id":"1","sysname":"snd_rpi_wsp","extlabel":"Wolfson Card Line Out","hwplatformid":"01","mixer_numid":"1","mixer_control":"HPOUT2 Digital","route_cmd":"/srv/http/command/wolfson.sh *CARDID* line_out > /dev/null"}');
$redis->sAdd('snd_rpi_wsp', '{"id":"2","sysname":"snd_rpi_wsp","extlabel":"Wolfson Card S&#47;PDIF Out","hwplatformid":"01","mixer_numid":"1","route_cmd":"/srv/http/command/wolfson.sh *CARDID* spdif_out > /dev/null"}');
$redis->sAdd('snd_rpi_wsp', '{"id":"3","sysname":"snd_rpi_wsp","extlabel":"Wolfson Card Headset Out","hwplatformid":"01","mixer_numid":"1","mixer_control":"HPOUT1 Digital","route_cmd":"/srv/http/command/wolfson.sh *CARDID* headset_out > /dev/null"}');
$redis->sAdd('snd_rpi_wsp', '{"id":"4","sysname":"snd_rpi_wsp","extlabel":"Wolfson Card Speakers Out","hwplatformid":"01","mixer_numid":"1","mixer_control":"Speaker Digital","route_cmd":"/srv/http/command/wolfson.sh *CARDID* speakers_out > /dev/null"}');

echo "Audio Cards database initialized\n";
