#!/bin/bash
export XDG_CACHE_HOME="/tmp/.cache" &
export DISPLAY=":0" &

# start the touchscreen calibration utility
# needed for some screens (Pollin 7" tft)
# for this to work you have to disable loading midori 
#xinput_calibrator &

# set power management options
xset dpms 0 0 0 &

#turn screensaver off
xset s off &

# turn off screensaver
xset -dpms &

# start the window manager without titlebar and mouse
matchbox-window-manager -use_titlebar no -use_cursor no &

# install multimedia keyboard shortcuts
xbindkeys &

# start chromium with fullscreen display
sudo -u http /etc/X11/xinit/start_chromium.sh
